name: Build eqalert

on: push

permissions:
    contents: read

jobs:
    build:
      strategy:
        fail-fast: false
        matrix:
          python-version: ["3.9.16"]
          poetry-version: ["1.7.1"]
          os: [ubuntu-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Manual pip installs
          run: |
              pip install --upgrade pip
              pip install --upgrade wheel
              pip install playsound 
        - name: Run image
          uses: abatilo/actions-poetry@v2
          with:
            poetry-version: ${{ matrix.poetry-version }}
        - name: View poetry --help
          run: poetry --help
          
        - name: Build package
          run: poetry build
        - name: Store build artifact
          uses: actions/upload-artifact@v4
          with:
            name: eqalert-bin
            path: dist/*.tar.gz
            retention-days: 1
      